novartis/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^app/", include("psoriassist.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psoriassist/urls.py
from django.conf.urls import url
from . import views

app_name = 'psoriassist'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^camera/$', views.TakePhoto.as_view(), name='camera'),
    url(r'^welcome/$', views.Welcome.as_view(), name='welcome'),
    url(r'^medication/$', views.Medication.as_view(), name='medication'),
    url(r'^emotional_management/$', views.Emotion_Management.as_view(), name='management'),
    url(r'^doctor/$', views.Doctor.as_view(), name='doctor'),
    url(r'^graphs/$', views.Graph.as_view(), name='graphs'),
    url(r'^medicine/$', views.Medicine.as_view(), name='medicine'),
    url(r'^sendata/$', views.SaveConversationHistory.as_view(), name='data'),
    url(r'^rload/$', views.ReloadWelcomePage.as_view(), name='rload'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    url(r'^telemed/$', views.TeleMed.as_view(), name='telemed')
]

psoriassist/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class AppUser(models.Model):
    user = models.OneToOneField(User)
    age = models.IntegerField(null=True)
    birthday = models.DateField(null=True)
    profile_picture = models.ImageField(null=True)
    last_doctor_appointment = models.DateField(null=True)
    bio = models.CharField(max_length=2000, null=True)
    isMentor = models.BooleanField()
    mentoree = models.ManyToManyField('AppUser')
    doctor = models.ManyToManyField('Doctor')

    def __str__(self):
        return self.user.username


class Message(models.Model):
    user = models.ForeignKey(AppUser, related_name='initialiseConvo')
    other_user = models.ForeignKey(AppUser, related_name='answerConvo')
    content = models.TextField()
    message_date = models.DateTimeField()
    delivered = models.BooleanField(default=False)

    def __str__(self):
        return self.message_date


class PASIScore(models.Model):
    user = models.ForeignKey(AppUser)
    score = models.CharField(max_length=100)

    def __str__(self):
        return self.user.user.username


class LesionSection(models.Model):
    section_name = models.CharField(max_length=100)
    PASI = models.ForeignKey(PASIScore)

    def __str__(self):
        return self.section_name


class Lesion(models.Model):
    user = models.ForeignKey(AppUser)
    name = models.CharField(null=True, max_length=500)
    image = models.CharField(max_length=2000, blank=True)
    lesion_location = models.ForeignKey(LesionSection, null=True)
    date_taken = models.DateTimeField(null=True)
    thickness = models.IntegerField(null=True)
    redness = models.IntegerField(null=True)
    scale = models.IntegerField(null=True)

    def __str__(self):
        return "%s- %s %s" % (self.user.user.username, self.name, self.date_taken)



class MentalState(models.Model):
    user = models.ForeignKey(AppUser)
    stress = models.IntegerField()
    anxiety = models.IntegerField()
    mood = models.IntegerField()
    date_taken = models.DateTimeField()

    def __str__(self):
        return "%s- %s" % (self.user.user.username, self.date_taken)

class Medication(models.Model):
    user = models.ForeignKey(AppUser)
    name = models.CharField(max_length=800)
    prescribed_by = models.ForeignKey('Doctor')
    date_prescribed = models.DateField()
    expiration_date = models.DateField()
    dosage = models.CharField(max_length=2000)
    other_info = models.TextField(max_length=2000)
    isCurrent = models.BooleanField()

    def __str__(self):
        return "%s- %s" % (self.user.user.username, self.name)

class Rating(models.Model):
    user = models.ManyToManyField(AppUser)
    medication = models.ForeignKey(Medication)
    effectiveness = models.SmallIntegerField(default=0)
    quality_of_life = models.SmallIntegerField(default=0)
    adherence = models.SmallIntegerField(default=0)

    def __str__(self):
        return "%s" % self.medication.name


class Doctor(models.Model):
    name = models.CharField(max_length=100)
    work_address = models.CharField(max_length=500)
    profile_picture = models.ImageField(null=True)
    distance_from_user = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Appointment(models.Model):
    user = models.ManyToManyField(AppUser)
    doctor = models.ManyToManyField(Doctor)
    date = models.DateTimeField()
    location = models.CharField( max_length=800)
    type_of_appointment = models.CharField(max_length=100)
    reason_for_appointment = models.TextField(max_length=2000)
    duration = models.TimeField()

    def __str__(self):
        return "%s %s %s" % (self.user.user.username, self.doctor.name, self.date)


class ComputerConversation(models.Model):
    user = models.ForeignKey(AppUser)
    date_sent = models.DateTimeField(auto_now_add=True)
    index = models.IntegerField(default=0)

    def __str__(self):
        return self.user.user.username

    #
    # def message_time(self):
    #     date_sent = datetime.now()
    #     return date_sent

# computer_message = models.TextField(max_length=2000, null=True)
#     user_message = models.CharField(max_length=2000, null=True)

psoriassist/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import View
from .models import AppUser, User, Lesion, ComputerConversation
from django.contrib import messages
import json


class Index(View):
    def get(self, request):
        return render(request, 'psoriassist/welcome.html')

class Medication(View):
    def get(self, request):
        return render(request, 'psoriassist/my_medication.html')

class Doctor(View):
    def get(self, request):
        return render(request, 'psoriassist/view_doctor.html')

class Profile(View):
    def get(self, request):
        return render(request, 'psoriassist/profile.html')

class Emotion_Management(View):
    def get(self, request):
        return render(request, 'psoriassist/manage_stress.html')

class TeleMed(View):
    def get(self, request):
        return render(request, 'psoriassist/video_call.html')

class TakePhoto(View):
    def get(self, request):
        return render(request, 'psoriassist/take_photo.html')


    def post(self, request):
        new_img = request.POST['image']
        username = request.POST['username']
        username = username[1:]
        print User.objects

        user_instance = User.objects.get(username=username)

        print user_instance

        app_user = AppUser.objects.get(user=user_instance)
        new_lesion_img = Lesion(user=app_user, image=new_img)
        new_lesion_img.save()

        messages.add_message(request, messages.SUCCESS, 'Thanks %s your image has been saved' % username)


class Welcome(View):
    def get(self, request):
        return render(request, 'psoriassist/welcome.html')

class Medicine(View):
    def get(self, request):
        return render(request, 'psoriassist/my_medication.html')

class Graph(View):
    def get(self, request):
        return render(request, 'psoriassist/graphs.html')


class SaveConversationHistory(View):
    def post(self, request):

        msg = json.loads(request.body)
        messages = msg['msg']
        username = msg['user']
        username = username[1:]
        index = messages['id']

        saved_convo = ComputerConversation.objects.filter(index=index)
        if not saved_convo:
            user_instance = User.objects.get(username=username)
            app_user_instance = AppUser.objects.get(user=user_instance)
            print user_instance

            new_conv = ComputerConversation(user=app_user_instance, index=index)
            new_conv.save()

        return HttpResponse(json.dumps({'result': 'success'}))


class ReloadWelcomePage(View):
    def get(self, request):
        conversations_id = []
        conversations = ComputerConversation.objects.all()
        print conversations

        for i in range(len(conversations)):
            conversations_id.append(conversations[i].index)

        ids = []
        for id in conversations_id:
            ids.append(id)

        return HttpResponse(json.dumps(ids))




novartis/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <li>
            <a class="username"><i class=" fa fa-user"></i> {% user_display request.user %}</a>
        </li>

        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>


    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

novartis/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 Psoriassist" %}

novartis/templates/_messages.html
{% load pinax_theme_bootstrap_tags %}
{% for message in messages %}
    <div class="alert fade in {% get_message_tags message %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}

novartis/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

novartis/templates/_styles.html
<link href='/site_media/static/css/site-e7b87bbea0.css' rel='stylesheet' />

novartis/templates/pagination/pagination.html
{# Includes django-pagination template #}
{# If you want to use django builtin pagination override this template #}
{# and include ``pagination/django_pagination_pagination.html`` instead. #}
{% include "pagination/django_pagination_pagination.html" %}

novartis/templates/pinax/announcements/announcement_detail.html
{% extends "site_base.html" %}

{% block head_title %}{{ announcement.title }}{% endblock %}

{% block body %}
    <h1>{{ announcement }}</h1>

{% endblock %}

novartis/templates/pinax/announcements/base.html
{% extends "site_base.html" %}

novartis/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}
{##}
{#{% block css %}{% endblock %}#}
{#{% block js %}{% endblock %}#}

{% block styles %}
    {% include "_styles.html" %}
{% endblock %}

{% block site_nav %}

{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}

{% block float_buttons %}
    {% if user.is_authenticated %}
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
            <i class="fa fa-hand-paper-o"></i>
        </a>

        <ul>
            <li><a href="{% url 'psoriassist:graphs' %}" class="btn-floating red"><i class="fa fa-line-chart"></i></a></li>
            <li><a href="{% url 'psoriassist:profile' %}" class="btn-floating yellow darken-1"><i class="fa fa-users"></i></a></li>
            <li><a href="{% url 'psoriassist:doctor' %}" class="btn-floating green"><i class="fa fa-stethoscope"></i></a></li>
            <li><a href="{% url 'psoriassist:medicine' %}" class="btn-floating blue"><i class="fa fa-medkit"></i></a></li>
            <li><a href="{% url 'psoriassist:index' %}" class="btn-floating purple"><i class="fa fa-comments"></i></a></li>
            <li><a href="{% url 'psoriassist:camera' %}" class="btn-floating orange"><i class="fa fa-camera"></i></a></li>
        </ul>
    </div>
    {% endif %}
{% endblock %}

psoriassist/templates/psoriassist/graphs.html
{% extends 'psoriassist/base.html' %}
{% block html %}
<html style="overflow: hidden;" lang="{{ LANGUAGE_CODE }}">
{% endblock %}
{% load staticfiles %}

{% block js %}
    <script src={% static 'js/graphs.js' %}></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href={% static 'css/graphs.css' %}>

{% endblock %}

{% block body %}
    <div style="margin-top: 60px;" id="main-container" class="cont container">
        <div class="row">
            <div class='col-md-8 col-md-offset-3'>
                <a href='{% url 'psoriassist:index' %}' style="position: relative; float: right; margin-top: 45px;" class="btn btn-success waves-effect waves-light conversation">Back to Chat</a>
                <h2 style="color: white">Progression Charts</h2>
            </div>
        </div>
        <div class="row move-it">
            <div class="col-lg-5 col-md-6 col-md-offset-3">

                <!--Rotating card-->
                <div class="card-wrapper">
                    <div id="card-1" class="card-rotating effect__click ">

                        <!--Front Side-->
                        <div class="face card-rotating__front z-depth-1">
                            <h4>Physical Lesion Progression Graph</h4>
                            <hr>

                            <div id = 'physical'>

                            </div>

                            <!--Triggering button-->
                            <a style="color: red; font-family: Roboto, sans-serif" class="rotate-btn" data-card="card-1"><i class="fa fa-repeat"> View Emotional
                                Progression Graph</i></a>
                        </div>
                        <!--/.Front Side-->

                        <!--Back Side-->
                        <div class="face card-rotating__back z-depth-1">
                            <h4>Emotional Progression Graph</h4>

{#                            <p class="card-content text-center"></p>#}
                            <hr>

                            <div id = 'emotional'>

                            </div>

                            <!--Triggering button-->
                            <a style="color: red;" class="rotate-btn" data-card="card-1"><i class="fa fa-undo"> View Physical Progression Graph</i></a>

                        </div>
                        <!--/.Back Side-->

                    </div>
                </div>
                <!--/.Rotating card-->

            </div>
        </div>
    </div>
{% endblock %}

psoriassist/templates/psoriassist/manage_stress.html
{% extends 'psoriassist/base.html' %}
{% load staticfiles %}

{% block js %}
    <script src={% static 'js/emotion.js' %}></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href={% static 'css/emotion.css' %}>

{% endblock %}

{% block body %}
    <div id="main-container" class="container">
        <div class="row">
            <div class='col-md-8 col-md-offset-3'>
                <h2>Manage Your Stress</h2>
                <a href='{% url 'psoriassist:index' %}' style="float: right; margin-top: 45px;" class="btn btn-success waves-effect waves-light conversation">Back to Chat</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-3">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/bhqU531xSN0?&autoplay=1"
                        frameborder="0" allowfullscreen></iframe>

            </div>
        </div>

        <div class="row">
            <a href='{% url 'psoriassist:index' %}' class="btn btn-success waves-effect waves-light conversation">Back
                to Chat</a>

            <div class="col-md-8 col-md-offset-1">
                <div id="myProgress">
                    <div id="myBar">
                        <div id="label">0%</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-1">
                <div id='completion'></div>
            </div>
        </div>
    </div>
{% endblock %}

psoriassist/templates/psoriassist/my_medication.html
{% extends 'psoriassist/base.html' %}
{% load staticfiles %}

{% block js %}

    <script src={% static 'js/medication.js' %}></script>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href={% static 'css/medication.css' %}>
{% endblock %}

{% block body %}
    <div id="main-container" class="container">
        <div class="row">
            <a href='{% url 'psoriassist:index' %}' style="float: right; margin-top: 45px;" class="btn btn-success waves-effect waves-light conversation">Back to Chat</a>
            <div class="col-md-12 col-md-offset-3">
                <h2 style="color:white; position: relative; bottom: 20px;"><b>Current Medication</b></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-5 col-md-6 col-md-offset-3">

                <!--Rotating card-->
                <div class="card-wrapper">
                    <div id="card-1" class="card-rotating effect__click ">

                        <!--Front Side-->
                        <div class="face card-rotating__front z-depth-1">
                            <div class="card-up">
                                <img src="{% static 'images/cosentyx.jpg' %}" class="img-responsive">
                            </div>
                            <h5 class="weight"><b>Date started:</b> 15/2/16</h5>
                            <h5 class="weight"><b>Prescription info:</b> 300 mg by injection once a week for four weeks</h5>

                            <!--Triggering button-->
                            <a class="rotate-btn " data-card="card-1"><i class="fa fa-repeat"> Click here to
                                rotate</i></a>
                        </div>
                        <!--/.Front Side-->

                        <!--Back Side-->
                        <div class="face card-rotating__back z-depth-1">
                            <h4 class = 'weight'>Medication Ratings</h4>

                            <p class="card-content text-center weight">For Cosentyx</p>
                            <hr>
                            <br> <b class="weight">Treatment effectiveness:</b>
                            <br>

                            <p style="color:orange;">7.8/10</p>
                            <br>
                            <br> <b class="weight">Average emotional wellness while on treatment</b>
                            <br>

                            <p style="color:green"> 8.7/10</p>
                            <br>
                            <br> <b class="weight">Adherence score</b>
                            <br>

                            <p style="color:green">8.5/10</p>

                            <!--Triggering button-->
                            <a class="rotate-btn " data-card="card-1"><i class="fa fa-undo"> Click here to rotate
                                back</i></a>

                        </div>
                        <!--/.Back Side-->

                    </div>
                </div>
                <!--/.Rotating card-->

            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-md-offset-3">
                <h1 style="position: relative;"><b>Past Medications</b></h1>
            </div>
        </div>

        <div class='row'>
            <div class="col-md-4">
                <!--Image Card-->
                <div class="card-wrapper">
                    <div id="card-2" class="card-rotating effect__click ">

                        <!--Front Side-->
                        <div class="face card-rotating__front z-depth-1">
                            <div class="card-up">
                                <img src="{% static 'images/dovonex.jpg' %}" class="img-responsive">
                            </div>
                            <p class="weight"><b>Date started:</b> 14/5/15</p>

                            <p class="weight"><b>Prescription info:</b> Apply a thin layer of Dovonex cream to the affected area. Do
                                not use two doses at once</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-2"><i class="fa fa-repeat"> Click here to
                                rotate</i></a>
                        </div>
                        <!--/.Front Side-->

                        <!--Back Side-->
                        <div class="face card-rotating__back z-depth-1">
                            <h4 class="weight">Medication Ratings</h4>

                            <p class="card-content text-center weight">For Dovonex</p>
                            <hr>
                            <br> <b class="weight">Treatment effectiveness:</b>
                            <br>

                            <p style="color:orange;">5.6/10</p>
                            <br>
                            <br> <b class="weight">Average emotional wellness while on treatment</b>
                            <br>

                            <p style="color:red"> 2.9/10</p>
                            <br>
                            <br> <b class="weight">Adherence score</b>
                            <br>

                            <p style="color:green">7.5/10</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-2"><i class="fa fa-undo"> Click here to rotate
                                back</i></a>

                        </div>
                        <!--/.Back Side-->

                    </div>
                </div>
            </div>

            <div class="col-md-4">

                <div class="card-wrapper">
                    <div id="card-3" class="card-rotating effect__click ">

                        <!--Front Side-->
                        <div class="face card-rotating__front z-depth-1">
                            <div class="card-up">
                                <img src="{% static 'images/Silkis.jpg' %}" class="img-responsive">
                            </div>
                            <p class="weight"><b class="weight">Date started:</b> 14/3/15</p>

                            <p class="weight"><b class="weight">Prescription info:</b> Ointment should be applied to the psoriasis affected areas
                                twice per day. Not more than 30 g of ointment should be used per day</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-3"><i class="fa fa-repeat"> Click here to
                                rotate</i></a>
                        </div>
                        <!--/.Front Side-->

                        <!--Back Side-->
                        <div class="face card-rotating__back z-depth-1">
                            <h4 class="weight">Medication Ratings</h4>

                            <p class="card-content text-center weight">For Silkis</p>
                            <hr>
                            <br> <b class="weight">Treatment effectiveness:</b>
                            <br>

                            <p style="color:red;">2.8/10</p>
                            <br>
                            <br> <b class="weight">Average emotional wellness while on treatment</b>
                            <br>

                            <p style="color:red"> 3.7/10</p>
                            <br>
                            <br> <b class="weight">Adherence score</b>
                            <br>

                            <p style="color:darkred">1.5/10</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-3"><i class="fa fa-undo"> Click here to rotate
                                back</i></a>

                        </div>
                        <!--/.Back Side-->

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-wrapper">
                    <div id="card-4" class="card-rotating effect__click ">

                        <!--Front Side-->
                        <div class="face card-rotating__front z-depth-1">
                            <div class="card-up">
                                <img src="{% static 'images/Eumovate.jpg' %}" class="img-responsive">
                            </div>
                            <p class="weight"><b>Date started:</b> 13/5/14</p>

                            <p class="weight"><b>Prescription info:</b> Apply thinly and gently rub in using only enough to
                                cover the entire affected area once or twice a day until improvement occurs</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-4"><i class="fa fa-repeat"> Click here to
                                rotate</i></a>
                        </div>
                        <!--/.Front Side-->

                        <!--Back Side-->
                        <div class="face card-rotating__back z-depth-1">
                            <h4 class="weight">Medication Ratings</h4>

                            <p class="card-content text-center weight">For Eumovate</p>
                            <hr>
                            <br> <b class="weight">Treatment effectiveness:</b>
                            <br>

                            <p style="color:lime;">9.8/10</p>
                            <br>
                            <br> <b class="weight">Average emotional wellness while on treatment</b>
                            <br>

                            <p style="color:darkred"> 1.7/10</p>
                            <br>
                            <br> <b class="weight">Adherence score</b>
                            <br>

                            <p style="color:orange">5.5/10</p>

                            <!--Triggering button-->
                            <a class="rotate-btn" data-card="card-4"><i class="fa fa-undo"> Click here to rotate
                                back</i></a>

                        </div>
                        <!--/.Back Side-->

                    </div>
                </div>
                <!--Image Card-->
            </div>

        </div>
    </div>

{% endblock %}


psoriassist/templates/psoriassist/view_doctor.html
{% extends 'psoriassist/base.html' %}
{% load staticfiles %}
{% block html %}
<html style="overflow: hidden;" lang="{{ LANGUAGE_CODE }}">
{% endblock %}

{% block js %}
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6BILxFTXEHVNL4ZqjS26UR5icHaVPjyE&libraries=places"></script>
    <script src={% static "js/jquery.datetimepicker.full.min.js" %}></script>
    <script src={% static 'js/doctor.js' %}></script>



{% endblock %}

{% block css %}
    <link rel="stylesheet" href={% static 'css/doctor.css' %}>
    <link rel="stylesheet" href={% static 'css/jquery.datetimepicker.css' %}>
{% endblock %}

{% block body %}
    <div id="main-container" class="container">
    <div class="row">
        <a href='{% url 'psoriassist:index' %}' style="float: right; margin-top: 45px;" class="btn btn-success waves-effect waves-light conversation">Back to Chat</a>
        <div class="col-md-8 col-md-offset-1">
            <span class="textAbove" style="position: relative; bottom: 50px;"><b>Current Doctor</b></span>
            <span class = 'textAbove' style="position: relative; bottom: 50px; float:right;"><b>Dermatologists Nearby</b></span>
        </div>
        <div class="col-md-8 col-md-offset-5">

            </div>
    </div>
    <div class='row fRow'>
        <div class="col-md-6">

            <!--Rotating card-->
            <div class="card-wrapper">
                <div id="card-1" class="card-rotating effect__click">

                    <!--Front Side-->
                    <div class="face card-rotating__front z-depth-1">
                        <div class="card-up">
                            <img src="{% static 'images/Ramat.jpg' %}" class="img-responsive">
                        </div>
                        <div class="avatar"><img
                                src="{% static 'images/friedman.jpg' %}"
                                class="img-circle img-responsive">
                        </div>
                        <h4>Dr. David Friedman</h4>

                        <!--Triggering button-->
                        <a class="rotate-btn" data-card="card-1" style="position: relative; bottom:
                            30px;"><i class="fa fa-repeat"> More Info/Schedule Appointment</i></a>
                    </div>
                    <!--/.Front Side-->

                    <!--Back Side-->
                    <div class="face card-rotating__back z-depth-1">
                        <h4>Dr. David Friedman, MD</h4>

{#                        <p class="card-content text-center">Phone: 03-612-2322#}
{#                            <br> Email: Tel-aviv@Drdavidfriedman.co.il</p>#}
                        <hr>
                        <b>Schedule an IN-PERSON visit:</b>
                        <br>
                        <br> Selected Date and Time: <input id="datetimepicker" type="text">
                        <br> <a class="btn btn-success btn-rounded waves-effect waves-light">Submit</a>
                        <hr>
                        <b>Schedule Telemedicine Consultation</b>
                        <br> Selected Date and Time: <input id="datetimepicker1" type="text">
                        <br><a href="{% url 'psoriassist:telemed' %}" class="btn btn-success btn-rounded waves-effect waves-light">Submit</a>
                        <br>

                        <!--Triggering button-->
                        <a style="font-family: Roboto, sans-serif;" class="r-button rotate-btn bottom" data-card="card-1"><i class="fa fa-undo"> Click here to rotate
                            back</i></a>


                    </div>
                    <!--/.Back Side-->

                </div>
            </div>
            <!--/.Rotating card-->

        </div>
        <div class='col-md-3'>
            <div id = 'map'></div>
        </div>
    </div>


    </div>
{% endblock %}